<?php

/**
 * @file
 * Contains global Live Parcels functions and store administration functionality.
 *
 * The store module is a container of sorts for various helper functions used
 * in different parts of the Ubercart core.  It also provides screens and
 * settings pages for use in store administration.
 */


/**
 * Implements hook_menu().
 */
function liveparcels_menu() {
  $items = array();

    $items['admin/liveparcels'] = array(
    'title' => 'Live Parcels',
    'description' => 'Administer Live Parcels .',
    'page callback' => 'liveparcels_configpage',
    'access arguments' => array('administer actions'),
    'weight' => -13,
    'file' => 'liveparcels.admin.inc',
  );
  $items['admin/liveparcels/settings'] = array(
    'title' => 'Live Parcels Setting',
    'description' => 'Administer Live Parcels settings.',
    'page callback' => 'liveparcels_admin_settings',
    'access arguments' => array('administer actions'),
    'weight' => -13,
    'file' => 'liveparcels.admin.inc',
  );
  $items['admin/liveparcels/message'] = array(
    'title' => 'Live Parcels Message',
    'description' => 'Administer Live Parcels Message.',
    'page callback' => 'drupal_get_form',
    'page arguments'=>array('liveparcels_admin_message_form'),
    'access arguments' => array('administer actions'),
    'weight' => -13,
    'file' => 'liveparcels.admin.inc',
  );
  
  $items['admin/liveparcels_updatefactor'] = array(
    'title' => 'Update factor',
    'description' => 'Update factor.',
    'page callback' => 'liveparcels_factor_settings',
    'access callback' => true,
    'file' => 'liveparcels.admin.inc',
  );

  
  $items['admin/liveparcels_managepackage'] = array(
    'title' => 'manage package  ',
    'description' => 'manage package.',
    'page callback' => 'liveparcels_managepackage',
    'access callback' => true,
    'file' => 'liveparcels.admin.inc',
  );
  $items['admin/liveparcels_fileupload'] = array(
    'title' => 'manage fileupload  ',
    'description' => 'manage fileupload.',
    'page callback' => 'liveparcels_fileupload',
    'access callback' => true,
    'file' => 'liveparcels.admin.inc',
  );
    $items['admin/liveparcels_zoneresult'] = array(
    'title' => 'manage zoneresult  ',
    'description' => 'manage zoneresult.',
    'page callback' => 'liveparcels_zoneresult',
    'access callback' => true,
    'file' => 'liveparcels.admin.inc',
  );
    $items['admin/liveparcels_updatezone'] = array(
    'title' => ' updatezone  ',
    'description' => ' updatezone.',
    'page callback' => 'liveparcels_updatezone',
    'access callback' => true,
    'file' => 'liveparcels.admin.inc',
  );
     $items['liveparcels/packageshow'] = array(
    'title' => ' package show  ',
    'description' => ' package show.',
    'page callback' => 'liveparcels_packageshow',
    'access callback' => true,
    'file' => 'liveparcels.inc',
  );
     $items['liveparcels/getpackageprice'] = array(
    'title' => ' package show  ',
    'description' => ' package show.',
    'page callback' => 'liveparcels_getPackageprice',
    'access callback' => true,
    'file' => 'liveparcels.inc',
  );
     $items['liveparcels/getzoneprice'] = array(
    'title' => ' package show  ',
    'description' => ' package show.',
    'page callback' => 'liveparcels_getZoneprice',
    'access callback' => true,
    'file' => 'liveparcels.inc',
  );
     $items['liveparcels/getzonelistdata'] = array(
    'title' => ' package show  ',
    'description' => ' package show.',
    'page callback' => 'liveparcels_getZonelistData',
    'access callback' => true,
    'file' => 'liveparcels.inc',
  );

  return $items;
}


