<?php
/**
 * @file
 * Contains global Live Parcels functions and store administration functionality.
 *
 * The store module is a container of sorts for various helper functions used
 * in different parts of the Ubercart core.  It also provides screens and
 * settings pages for use in store administration.
 */

/**
 * Implements hook_menu().
 */
function lp_parcel_menu(){
    $items=array();
    $items['node/%node/order_view'] = array(
    'title' => 'View Order',
    'menu_name'=>'liveparcels_view_order',
    'description' => ' View Order.',
    'page callback' => array('lp_parcel_order_view'),
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'node_access',
    'access arguments' => array('view', 1),
  );
  return $items;
}

function lp_parcel_order_view($node){
 
  $order_id=isset($node->field_parcel_order_id[$node->language][0]['value']) && $node->field_parcel_order_id[$node->language][0]['value'] > 0 ? $node->field_parcel_order_id[$node->language][0]['value']:0;
  if($order_id>0 ){
    header("Location: /user/".$node->uid."/orders/".$order_id);
    exit;
    }else{
        drupal_set_message('This node is not a live parcel. so it no order id', 'error');
       header("Location: ".$_SERVER["HTTP_HOST"]."/node/".$node->nid);  
    }
}
/**
 * Implements hook_uc_checkout_pane().
 create liveparcels extra pane 
 * */
function lp_parcel_uc_checkout_pane_parcel_pickup($op, $order, $form = NULL, &$form_state = NULL){
        $parcels=liveparcels_getparcelsdata();
   drupal_add_css(drupal_get_path('module', 'lp_parcel') . '/lp_parcel.css',array('group' => CSS_DEFAULT, 'every_page' => TRUE));
     if($parcels){
      switch ($op) {
        case 'view':        
            $parceldata=lp_parcel_get_parcel_data($order->order_id);
    $extra_info=$parceldata['extra_info'];
    
    date_default_timezone_set(variable_get('date_default_timezone'));

    if(is_array($extra_info) && count($extra_info)>0){
        $pickup_extra=array();
          if($parcels['ptype']=="1"){
            for($f=0;$f<count($parcels['parcels']);$f++){
               $pickup_extra[$f]=array('parcel_title'=>array('#markup'=>'<h2>'.$parcels['parcels'][$f]['parcelnum'].'</h2>'),'field_parcel_pickup_address_data'=>lp_parcel_get_parcel_address($parcels,'pickup',$f,$extra_info['pickupdata'][$f]['field_parcel_pickup_address']),
               'field_pick_up_time'=> array(
                  '#title' => t('Pickup time'),
                  '#type' => 'date_popup', 
                  '#date_format' => 'm/d/Y', 
                  '#date_year_range' => '0:+2', 
                  '#datepicker_options' => array('minDate' => variable_get('liveparcels_pickup_time',0)."D"),
                  '#required' => TRUE,
                  '#default_value' => $extra_info['pickupdata'][$f]['field_pick_up_time'], // Default value must be in 'Y-m-d' format.
                ),'field_pick_up_time_ampm'=>array(
               '#type' => 'select',
               '#title' => '',
               '#options' => array(
                  'AM' => t('AM'),
                 'PM' => t('PM'),
               ),'#default_value' => $extra_info['pickupdata'][$f]['field_pick_up_time_ampm'],
               '#attributes' => array('class'=>array('pick_up_time_ampm')),
               ),'field_customer_reference'=>array(
                '#type' => 'textfield',
                '#title' => t('Customer reference'),
                '#default_value' =>'',
                '#description' => t('Enter any reference number here to help you find this item.')
                ),'field_cash_to_collect'=>array(
                '#type' => 'textfield',
                '#title' => t('Cash to collect'),
                '#default_value' =>$extra_info['pickupdata'][$f]['field_cash_to_collect'],
                 '#size'=>'30',
                  '#maxlength'=>'30',
                  '#attributes' => array('class'=>array('pickup_cash_to_collect')),
                '#description' => t('Enter the amount of cash you would like us to collect on your behalf and deliver to you.')
                  ),'field_pickup_note'=>array(
                '#title' => t('Pickup Note'),
                '#type' => 'textarea',
                '#description' => t('Enter any information here that would assist with the pick up process'),
                '#default_value' =>$extra_info['pickupdata'][$f]['field_pickup_note'],
                '#attributes' => array('class'=>array('pickup_note')),
                ));
            }

        }else{
                $pickup_extra[0]=array('field_parcel_pickup_address_data'=>lp_parcel_get_parcel_address($parcels,'pickup',0,$extra_info['pickupdata'][0]['field_parcel_pickup_address']),'field_pick_up_time'=> array(
                  '#title' => t('Pickup time'),
                  '#type' => 'date_popup', 
                  '#date_format' => 'm/d/Y', 
                  '#date_year_range' => '0:+2', 
                   '#datepicker_options' => array('minDate' => variable_get('liveparcels_pickup_time',0)."D"),
                  '#required' => TRUE,
                  '#default_value' => $extra_info['pickupdata'][0]['field_pick_up_time'], // Default value must be in 'Y-m-d' format.
                ),'field_pick_up_time_ampm'=>array(
               '#type' => 'select',
               '#title' => '',
               '#options' => array(
                  'AM' => t('AM'),
                 'PM' => t('PM'),
               ),
               '#default_value' => $extra_info['pickupdata'][0]['field_pick_up_time_ampm'],
               '#attributes' => array('class'=>array('pick_up_time_ampm')),
               ),'field_cash_to_collect'=>array(
                '#type' => 'hiddden',
                '#title' => t('Cash to collect'),
                '#default_value' =>'',
                '#size'=>'30',
                '#maxlength'=>'30',
                '#attributes' => array('class'=>array('pickup_cash_to_collect')),
                '#description' => t('Enter the amount of cash you would like us to collect on your behalf and deliver to you.')
                  ),'field_pickup_note'=>array(
                '#title' => t('Pickup Note'),
                '#type' => 'textarea',
                '#description' => t('Enter any information here that would assist with the pick up process'),
                '#default_value' =>$extra_info['pickupdata'][0]['field_pickup_note'],
                '#attributes' => array('class'=>array('pickup_note')),
                ));
        } 
    }else{
       $pickup_extra=array();
        if($parcels['ptype']=="1"){
            for($f=0;$f<count($parcels['parcels']);$f++){
               $pickup_extra[$f]=array('parcel_title'=>array('#markup'=>'<h2>'.$parcels['parcels'][$f]['parcelnum'].'</h2>'),'field_parcel_pickup_address_data'=>lp_parcel_get_parcel_address($parcels,'pickup',$f),
               'field_pick_up_time'=> array(
                  '#title' => t('Pickup time'),
                  '#type' => 'date_popup', 
                  '#date_format' => 'm/d/Y', 
                  '#date_year_range' => '0:+2', 
                   '#datepicker_options' => array('minDate' => variable_get('liveparcels_pickup_time',0)."D"),
                  '#required' => TRUE,
                  '#default_value' =>date("Y-m-d",time(date("Y-m-d"))+3600*24*variable_get('liveparcels_pickup_time',0)), // Default value must be in 'Y-m-d' format.
                ),'field_pick_up_time_ampm'=>array(
               '#type' => 'select',
               '#title' => '',
               '#options' => array(
                  'AM' => t('AM'),
                 'PM' => t('PM'),
               ),'#default_value' => 'AM',
               '#attributes' => array('class'=>array('pick_up_time_ampm')),
               ),'field_customer_reference'=>array(
                '#type' => 'textfield',
                '#title' => t('Customer reference'),
                '#default_value' =>'',
                '#description' => t('Enter any reference number here to help you find this item.')
                ),'field_cash_to_collect'=>array(
                '#type' => 'textfield',
                '#title' => t('Cash to collect'),
                '#default_value' =>'',
                 '#size'=>'30',
                  '#maxlength'=>'30',
                  '#attributes' => array('class'=>array('pickup_cash_to_collect')),
                '#description' => t('Enter the amount of cash you would like us to collect on your behalf and deliver to you.')
                  ),'field_pickup_note'=>array(
                '#title' => t('Pickup Note'),
                '#type' => 'textarea',
                '#description' => t('Enter any information here that would assist with the pick up process'),
                '#default_value' =>'',
                '#attributes' => array('class'=>array('pickup_note')),
                ));
            }

        }else{
         $pickup_extra[0]=array('field_parcel_pickup_address_data'=>lp_parcel_get_parcel_address($parcels,'pickup',0),'field_pick_up_time'=> array(
                  '#title' => t('Pickup time'),
                  '#type' => 'date_popup', 
                  '#date_format' => 'm/d/Y', 
                  '#date_year_range' => '0:+2', 
                  '#datepicker_options' => array('minDate' => variable_get('liveparcels_pickup_time',0)."D"),
                  '#required' => TRUE,
                  '#default_value' => date("Y-m-d",time(date("Y-m-d"))+3600*24*variable_get('liveparcels_pickup_time',0)), // Default value must be in 'Y-m-d' format.
                ),'field_pick_up_time_ampm'=>array(
               '#type' => 'select',
               '#title' => '',
               '#options' => array(
                  'AM' => t('AM'),
                 'PM' => t('PM'),
               ),
               '#default_value' => 'AM',
               '#attributes' => array('class'=>array('pick_up_time_ampm')),
               ),'field_cash_to_collect'=>array(
                '#type' => 'hiddden',
                '#title' => t('Cash to collect'),
                '#default_value' =>'',
                '#size'=>'30',
                '#maxlength'=>'30',
                '#attributes' => array('class'=>array('pickup_cash_to_collect')),
                '#description' => t('Enter the amount of cash you would like us to collect on your behalf and deliver to you.')
                  ),'field_pickup_note'=>array(
                '#title' => t('Pickup Note'),
                '#type' => 'textarea',
                '#description' => t('Enter any information here that would assist with the pick up process'),
                '#default_value' =>'',
                '#attributes' => array('class'=>array('pickup_note')),
                ));
        } 
    }
        $contents=$pickup_extra;
          return array('contents' => $contents);
      
            case 'process':
                $parcel_pickup = $form_state['values']['panes']['parcel_pickup'];
                $parcel_delivery = $form_state['values']['panes']['parcel_delivery'];
                foreach($parcel_pickup as $key=>$pinfo){
                     if (empty($pinfo['field_parcel_pickup_address_data']['address']['first_name']) ) {
                        form_set_error('panes][parcel_pickup]['.$key.'][field_parcel_pickup_address_data][address][first_name', t('Parcel#'.($key+1).': must enter pickup first name.'));
                    }
                    if (empty($pinfo['field_parcel_pickup_address_data']['address']['last_name']) ) {
                        form_set_error('panes][parcel_pickup]['.$key.'][field_parcel_pickup_address_data][address][last_name', t('Parcel#'.($key+1).': must enter pickup last name.'));
                    }
                    if (empty($pinfo['field_parcel_pickup_address_data']['address']['street1']) ) {
                        form_set_error('panes][parcel_pickup]['.$key.'][field_parcel_pickup_address_data][address][street1', t('Parcel#'.($key+1).': must enter pickup street.'));
                    }
                    if (!empty($pinfo['field_parcel_pickup_address_data']['address']['phone']) && !is_numeric($pinfo['field_parcel_pickup_address_data']['address']['phone'])) {
                        form_set_error('panes][parcel_pickup]['.$key.'][field_parcel_pickup_address_data][address][phone', t('Parcel#'.($key+1).': must enter number.'));
                    }
                    if (empty($pinfo['field_pick_up_time']) ||(!empty($pinfo['field_pick_up_time']) && strtotime($pinfo['field_pick_up_time']) < strtotime(date("Y-m-d"))+3600*24*variable_get('liveparcels_pickup_time',0)) ) {
                        form_set_error('panes][parcel_pickup]['.$key.'][field_pick_up_time', t('Parcel#'.($key+1).': You must select a pickup time '.variable_get('liveparcels_pickup_time',0).' days from now. '));
                    }   
                }
                foreach($parcel_delivery as $key=>$pinfo){
                     if (empty($pinfo['field_parcel_delivery_address_data']['address']['first_name']) ) {
                        form_set_error('panes][parcel_delivery]['.$key.'][field_parcel_delivery_address_data][address][first_name', t('Parcel#'.($key+1).': must enter delivery first name.'));
                    }
                    if (empty($pinfo['field_parcel_delivery_address_data']['address']['last_name']) ) {
                        form_set_error('panes][parcel_delivery]['.$key.'][field_parcel_delivery_address_data][address][last_name', t('Parcel#'.($key+1).': must enter delivery last name.'));
                    }
                    if (empty($pinfo['field_parcel_delivery_address_data']['address']['street1']) ) {
                        form_set_error('panes][parcel_delivery]['.$key.'][field_parcel_delivery_address_data][address][street1', t('Parcel#'.($key+1).': must enter delivery street name.'));
                    }
                    if (!empty($pinfo['field_parcel_delivery_address_data']['address']['phone']) && !is_numeric($pinfo['field_parcel_delivery_address_data']['address']['phone'])) {
                        form_set_error('panes][parcel_delivery]['.$key.'][field_parcel_delivery_address_data][address][phone', t('Parcel#'.($key+1).': must enter number.'));
                    }
                }
                return true;
        }
    }
}
/**
 * Implements hook_uc_checkout_pane().
 create liveparcels extra pane 
 * */
function lp_parcel_uc_checkout_pane_parcel_delivery($op, $order, $form = NULL, &$form_state = NULL){
        $parcels=liveparcels_getparcelsdata();
     if($parcels){
      switch ($op) {
        case 'view':      
             
        if(module_exists('lp_address')){  
          drupal_add_js(drupal_get_path('module', 'lp_address') . '/lp_address.js');
          }
    $parceldata=lp_parcel_get_parcel_data($order->order_id);
    $extra_info=$parceldata['extra_info'];
    if(is_array($extra_info) && count($extra_info)>0){
        $delivery_extra=array();
        if($parcels['ptype']=="1"){
             $delivery_extra[0]=array('field_parcel_delivery_address_data'=>lp_parcel_get_parcel_address($parcels,'delivery',0,$extra_info['deliverydata'][0]['field_parcel_delivery_address']),'field_authority_to_leave'=>array(
              '#title' => t('Authority to leave'),
                '#type' =>'checkbox', 
                '#default_value'=>$extra_info['deliverydata'][0]['field_authority_to_leave'],
                '#attributes' => array('class'=>array('authority_to_leave')),
                  ),'field_delivery_note'=>array(
                '#title' => t('Delivery Note'),
                '#type' => 'textarea',
                '#description' => t('Enter any information here that would assist with the delivery process'),
                '#default_value' =>$extra_info['deliverydata'][0]['field_delivery_note'],
                '#attributes' => array('class'=>array('delivery_note')),
                ));
        }else{
            for($f=0;$f<count($parcels['parcels']);$f++){
                   $delivery_extra[$f]=array('parcel_title'=>array('#markup'=>'<h2>'.$parcels['parcels'][$f]['parcelnum'].'</h2>'),'field_parcel_delivery_address_data'=>lp_parcel_get_parcel_address($parcels,'delivery',$f,$extra_info['deliverydata'][$f]['field_parcel_delivery_address']),
                   'field_authority_to_leave'=>array(
                    '#title' => t('Authority to leave'),
                    '#type' =>'checkbox', 
                    '#default_value'=>$extra_info['deliverydata'][$f]['field_authority_to_leave'],
                    '#attributes' => array('class'=>array('authority_to_leave')),
                      ),'field_customer_reference'=>array(
                        '#type' => 'textfield',
                        '#title' => t('Customer reference'),
                        '#default_value' =>$extra_info['deliverydata'][$f]['field_customer_reference'],
                        '#description' => t('Enter any reference number here to help you find this item.')
                      ),'field_delivery_note'=>array(
                    '#title' => t('Delivery Note'),
                    '#type' => 'textarea',
                    '#description' => t('Enter any information here that would assist with the delivery process'),
                    '#default_value' =>$extra_info['deliverydata'][$f]['field_delivery_note'],
                     '#attributes' => array('class'=>array('delivery_note')),
                    ));
            }
        }
    }else{
        $delivery_extra=array();
        if($parcels['ptype']=="1"){
             $delivery_extra[0]=array('field_parcel_delivery_address_data'=>lp_parcel_get_parcel_address($parcels,'delivery',0),'field_authority_to_leave'=>array(
              '#title' => t('Authority to leave'),
                '#type' =>'checkbox', 
                '#attributes' => array('class'=>array('authority_to_leave')),
                  ),'field_delivery_note'=>array(
                '#title' => t('Delivery Note'),
                '#type' => 'textarea',
                '#description' => t('Enter any information here that would assist with the delivery process'),
                '#default_value' =>'',
                '#attributes' => array('class'=>array('delivery_note')),
                ));
        }else{
            for($f=0;$f<count($parcels['parcels']);$f++){
                   $delivery_extra[$f]=array('parcel_title'=>array('#markup'=>'<h2>'.$parcels['parcels'][$f]['parcelnum'].'</h2>'),'field_parcel_delivery_address_data'=>lp_parcel_get_parcel_address($parcels,'delivery',$f),
                   'field_authority_to_leave'=>array(
                    '#title' => t('Authority to leave'),
                    '#type' =>'checkbox', 
                    '#attributes' => array('class'=>array('authority_to_leave')),
                      ),'field_customer_reference'=>array(
                        '#type' => 'textfield',
                        '#title' => t('Customer reference'),
                        '#default_value' =>'',
                        '#description' => t('Enter any reference number here to help you find this item.')
                      ),'field_delivery_note'=>array(
                    '#title' => t('Delivery Note'),
                    '#type' => 'textarea',
                    '#description' => t('Enter any information here that would assist with the delivery process'),
                    '#default_value' =>'',
                     '#attributes' => array('class'=>array('delivery_note')),
                    ));
            }
        }
    }
           $contents=$delivery_extra;
          
          return array('contents' => $contents);
        case 'process':
        if(module_exists('lp_address')){  
          drupal_add_js(drupal_get_path('module', 'lp_address') . '/lp_address.js');
          }
        $pickupdata=array();
        $deliverydata=array();
           if($parcels['ptype']==1){
              
                 foreach($parcels['parcels'] as $key=>$val){
                    //$pickup_address_id=lp_parcel_update_parcel_address($form_state['values']['panes']['parcel_pickup'][$key]['field_parcel_pickup_address_data']);
                    $pickupdata[$key]=@array('field_parcel_pickup_address'=>$form_state['values']['panes']['parcel_pickup'][$key]['field_parcel_pickup_address_data'],'field_pick_up_time'=>$form_state['values']['panes']['parcel_pickup'][$key]['field_pick_up_time'],'field_pick_up_time_ampm'=>$form_state['values']['panes']['parcel_pickup'][$key]['field_pick_up_time_ampm'],'field_cash_to_collect'=>$form_state['values']['panes']['parcel_pickup'][$key]['field_cash_to_collect'],'field_pickup_note'=>$form_state['values']['panes']['parcel_pickup'][$key]['field_pickup_note']);
                }
                // $delivery_address_id=lp_parcel_update_parcel_address($form_state['values']['panes']['parcel_delivery'][0]['field_parcel_delivery_address_data']);
                $deliverydata[0]=@array('field_parcel_delivery_address'=>$form_state['values']['panes']['parcel_delivery'][0]['field_parcel_delivery_address_data'],'field_authority_to_leave'=>$form_state['values']['panes']['parcel_delivery'][0]['field_authority_to_leave'],'field_customer_reference'=>$form_state['values']['panes']['parcel_delivery'][0]['field_customer_reference'],'field_delivery_note'=>$form_state['values']['panes']['parcel_delivery'][0]['field_delivery_note']);
            }else{

               // $pickup_address_id=lp_parcel_update_parcel_address($form_state['values']['panes']['parcel_pickup'][0]['field_parcel_pickup_address_data']);
                $pickupdata[0]=@array('field_parcel_pickup_address'=>$form_state['values']['panes']['parcel_pickup'][0]['field_parcel_pickup_address_data'],'field_pick_up_time'=>$form_state['values']['panes']['parcel_pickup'][0]['field_pick_up_time'],'field_pick_up_time_ampm'=>$form_state['values']['panes']['parcel_pickup'][0]['field_pick_up_time_ampm'],'field_cash_to_collect'=>$form_state['values']['panes']['parcel_pickup'][0]['field_cash_to_collect'],'field_pickup_note'=>$form_state['values']['panes']['parcel_pickup'][0]['field_pickup_note']);
                 foreach($parcels['parcels'] as $key=>$val){
                    //$delivery_address_id=lp_parcel_update_parcel_address($form_state['values']['panes']['parcel_delivery'][$key]['field_parcel_delivery_address_data']);
                    $deliverydata[$key]=@array('field_parcel_delivery_address'=>$form_state['values']['panes']['parcel_delivery'][$key]['field_parcel_delivery_address_data'],'field_authority_to_leave'=>$form_state['values']['panes']['parcel_delivery'][$key]['field_authority_to_leave'],'field_customer_reference'=>$form_state['values']['panes']['parcel_delivery'][$key]['field_customer_reference'],'field_delivery_note'=>$form_state['values']['panes']['parcel_delivery'][$key]['field_delivery_note']);
                }
        }
        $parceldata=array('pickupdata'=>$pickupdata,'deliverydata'=>$deliverydata);
         db_update('liveparcels_order')->fields(array('extra_info' => serialize($parceldata)))->condition('order_id',$order->order_id , '=')->execute();
   case 'review':   
      }
    }
}
/*
 * get_parcel_address($parcel_info,'pickup')
 * parcels info,parcels type
 * */
function lp_parcel_get_parcel_address($parcel_info,$parcel_type='pickup',$key='0',$default_info=array()){
        if(module_exists('lp_address')){
            return  lp_address_address_view($parcel_info,$parcel_type,$key,$default_info);
        }else{
        return array();    
        }
}
/*
 * update_parcel_address($address)
 * parcels address info
 * */
function lp_parcel_update_parcel_location($address){
        if(module_exists('lp_address')){
            return  lp_address_location_update($address);
        }else{
        return 0;    
        }
}
/*
 * update_parcel_address($address)
 * parcels address info,user id
 * */
function lp_parcel_update_parcel_address($address,$uid){
        if(module_exists('lp_address')){
            return  lp_address_address_update($address,$uid);
        }else{
        return 0;    
        }
}

/*
 * lp_parcel_table theme
 * */
function theme_lp_parcel_table($variables) {
    $parcels = $variables['items'];
 
  // Set up table rows.
    foreach ($parcels['parcels'] as $parcel ) {
        
      $rows[] = array(
        array('data' => $parcel['parcelnum'], 'class' => array('products')),
        array('data' => $parcel['dimfirst'].'x'.$parcel['dimsecond'].'x'.$parcel['dimthree'].' cm','class' => array('price')),
     
      );
    }

  // Add the subtotal as the final row.
    $rows[] = array(
      'data' => array(
        // One cell
        array(
          'data' => array(
            '#theme' => 'uc_price',
            '#prefix' => '<span id="subtotal-title">' . t('Subtotal:') . '</span> ',
            '#price' => $parcels['totals'],
          ),
          // Cell attributes
          'colspan' => 4,
          'class' => array('subtotal'),
        ),
      ),
      // Row attributes
      'class' => array('subtotal'),
    );
  return theme('table', array( 'rows' => $rows, 'attributes' => array('class' => array('lp_parcel_table'))));
}
/**
 * Implements hook_uc_checkout_pane().
 */
function lp_parcel_uc_checkout_pane() {
   
      $panes['parcel_pickup'] = array(
      'callback' => 'lp_parcel_uc_checkout_pane_parcel_pickup',
    'title' => t('Parcel pickup extra contents'),
    'desc' => t("Display the contents of a customer's shopping cart."),
      'enabled' => FALSE,
      'weight' => 4,
      );
      $panes['parcel_delivery'] = array(
      'callback' => 'lp_parcel_uc_checkout_pane_parcel_delivery',
    'title' => t('Parcel delivery extra contents'),
    'desc' => t("Display the contents of a customer's shopping cart."),
      'enabled' => FALSE,
      'weight' => 5,
      );
       
  return $panes;    
}
function lp_parcel_uc_checkout_complete($order, $account) {
    
      $parcels=liveparcels_getparcelsdata();
            if(module_exists('lp_discount')){
            $parcels['discount']=lp_discount_get_pricing($parcels['totals']);
            $order_total=$parcels['totals']-$parcels['discount'];
        }else{
            $order_total=$parcels['totals'];
        }
     db_update('uc_orders')->fields(array('order_total' => $order_total))->condition('order_id',$order->order_id , '=')->execute();
    db_update('uc_order_products')->fields(array('price' => $parcels['totals']))->condition('order_id',$order->order_id , '=')->execute();
    $order_id=$order->order_id;
    $parceldata=lp_parcel_get_parcel_data($order_id);
    $parcel_info=$parceldata['parcel_info'];
    $extra_info=$parceldata['extra_info'];

    
    foreach($parcel_info['parcels'] as $key=>$parcel){
        
        $newnode = new stdClass();
       $newnode->uid=$order->uid;
       $newnode->language='und';
       $newnode->title='Order#'.$order_id.$parcel['parcelnum'];
       $newnode->type='live_parcel';
       $newnode->status=1;
        $newnode->comment=2;
       node_save($newnode);
       
        $node = node_load($newnode->nid);

       $node->field_parcel_size[$node->language][0]['value'] =$parcel['dimfirst'].'x'.$parcel['dimsecond'].'x'.$parcel['dimthree'].' cm';
       $node->field_parcel_package_name[$node->language][0]['value'] =$parcel['package_name'];
        $node->field_parcel_weight[$node->language][0]['value'] =round($parcel['weighttext'],1);
        $node->field_parcel_price[$node->language][0]['value'] =str_replace(variable_get('uc_currency_sign','$'),'',$parcel['price']);
        $node->field_parcel_order_id[$node->language][0]['value'] =$order_id;

          if($parcel_info['ptype']=='1' ){
               $pickup_address_id=lp_parcel_update_parcel_address($extra_info['pickupdata'][$key]['field_parcel_pickup_address'],$order->uid);
               $delivery_address_id=$key>0 ? $delivery_address_id : lp_parcel_update_parcel_address($extra_info['deliverydata'][0]['field_parcel_delivery_address'],$order->uid);
               
               $pickup_location_id=lp_parcel_update_parcel_location($extra_info['pickupdata'][$key]['field_parcel_pickup_address'],$order->uid);
               
               $delivery_location_id=$key>0 ? $delivery_location_id : lp_parcel_update_parcel_location($extra_info['deliverydata'][0]['field_parcel_delivery_address'],$order->uid);
              
                $field_pickup_first_name=$extra_info['pickupdata'][$key]['field_parcel_pickup_address']['address']['first_name'];
                $field_pickup_last_name=$extra_info['pickupdata'][$key]['field_parcel_pickup_address']['address']['last_name'];
                
                $field_delivery_first_name=$extra_info['deliverydata'][0]['field_parcel_delivery_address']['address']['first_name'];
                $field_delivery_last_name=$extra_info['deliverydata'][0]['field_parcel_delivery_address']['address']['last_name'];
                
              $field_pick_up_time=$extra_info['pickupdata'][$key]['field_pick_up_time'];
              $field_pick_up_time_ampm=$extra_info['pickupdata'][$key]['field_pick_up_time_ampm'];
              $field_cash_to_collect=$extra_info['pickupdata'][$key]['field_cash_to_collect'];
              $field_pickup_note=$extra_info['pickupdata'][$key]['field_pickup_note'];
              
              $field_authority_to_leave=$extra_info['deliverydata'][0]['field_authority_to_leave'];
              $field_customer_reference=$extra_info['deliverydata'][0]['field_customer_reference'];
              $field_delivery_note=$extra_info['deliverydata'][0]['field_delivery_note'];
              
            }else{
                
                $pickup_address_id=$key>0 ? $pickup_address_id : lp_parcel_update_parcel_address($extra_info['pickupdata'][0]['field_parcel_pickup_address'],$order->uid);
                $delivery_address_id=lp_parcel_update_parcel_address($extra_info['deliverydata'][$key]['field_parcel_delivery_address'],$order->uid);

               $pickup_location_id= $key>0 ? $pickup_location_id :lp_parcel_update_parcel_location($extra_info['pickupdata'][0]['field_parcel_pickup_address'],$order->uid);
               
               $delivery_location_id= lp_parcel_update_parcel_location($extra_info['deliverydata'][$key]['field_parcel_delivery_address'],$order->uid);
              
              
                $field_pickup_first_name=$extra_info['pickupdata'][0]['field_parcel_pickup_address']['address']['first_name'];
                $field_pickup_last_name=$extra_info['pickupdata'][0]['field_parcel_pickup_address']['address']['last_name'];

                
                $field_delivery_first_name=$extra_info['deliverydata'][$key]['field_parcel_delivery_address']['address']['first_name'];
                $field_delivery_last_name=$extra_info['deliverydata'][$key]['field_parcel_delivery_address']['address']['last_name'];
                
                $field_pick_up_time=$extra_info['pickupdata'][0]['field_pick_up_time'];
                $field_pick_up_time_ampm=$extra_info['pickupdata'][0]['field_pick_up_time_ampm'];
                $field_cash_to_collect=$extra_info['pickupdata'][0]['field_cash_to_collect'];
                $field_pickup_note=$extra_info['pickupdata'][0]['field_pickup_note'];

                $field_authority_to_leave=$extra_info['deliverydata'][$key]['field_authority_to_leave'];
                $field_customer_reference=$extra_info['deliverydata'][$key]['field_customer_reference'];
                $field_delivery_note=$extra_info['deliverydata'][$key]['field_delivery_note'];
          }
        $node->field_pickup_location[$node->language][0]['lid'] =$pickup_location_id;
        $node->field_delivery_location[$node->language][0]['lid'] =$delivery_location_id;
        
        $node->field_pickup_first_name[$node->language][0]['value'] =$field_pickup_first_name;
        $node->field_pickup_last_name[$node->language][0]['value'] =$field_pickup_last_name;

        
        $node->field_delivery_first_name[$node->language][0]['value'] =$field_delivery_first_name;
        $node->field_delivery_last_name[$node->language][0]['value'] =$field_delivery_last_name;

        
        $node->field_pick_up_time[$node->language][0]['value'] =$field_pick_up_time;
        $node->field_pick_up_time_ampm[$node->language][0]['value'] =$field_pick_up_time_ampm;
        $node->field_cash_to_collect[$node->language][0]['value'] =intval($field_cash_to_collect)>0 ? intval($field_cash_to_collect):0;
        $node->field_pickup_note[$node->language][0]['value'] =$field_pickup_note;
        
        $node->field_authority_to_leave[$node->language][0]['value'] =$field_authority_to_leave;
        $node->field_customer_reference[$node->language][0]['value'] =$field_customer_reference;
        $node->field_delivery_note[$node->language][0]['value'] =$field_delivery_note;
        
          node_save($node);
    }
      
 $cart_id=uc_cart_get_id();
 db_delete("liveparcels_cart")->condition('cart_id',$cart_id, '=')->execute(); 
}
function lp_parcel_get_parcel_data($order_id){
    $pdata=db_query("SELECT `parcel_info`,`extra_info` FROM `liveparcels_order` WHERE `order_id`='$order_id'")->fetchAssoc();
    $parceldata=array("parcel_info"=>unserialize($pdata['parcel_info']),"extra_info"=>unserialize($pdata['extra_info']));
    return  $parceldata;    
}

/*if product_id is liveparcel,checkout cart pane hiddren*/
function lp_parcel_uc_checkout_pane_alter(&$panes) {
     $parcels=liveparcels_getparcelsdata();
     if($parcels){
          $panes['parcel_pickup']['enabled'] = true;
          $panes['parcel_delivery']['enabled'] = true;
    }else{
        $panes['parcel_pickup']['enabled'] = false;
          $panes['parcel_delivery']['enabled'] = false;
       
    }
}
function  lp_parcel_form_uc_cart_checkout_form_alter(&$form,&$form_state){
 $form['actions']['cancel']=array(
    '#type' => 'button',
    '#value' => t('Cancel'),
    '#attributes'=>array("onclick"=>"location.href='/cart'")
  );  
  return   $form;   
}


