<?php
// $Id$
/**
* Implementation of hook_install().
*/
function lp_testdata_install() {
$templine='';
$file_path1 = drupal_get_path('module','lp_testdata').'/liveparcels_package.sql';
$file_path2 = drupal_get_path('module','lp_testdata').'/liveparcels_zone_post.sql';
$file_path3 = drupal_get_path('module','lp_testdata').'/liveparcels_zone_price.sql';

$file_array = array($file_path1 ,$file_path2 ,$file_path3);

 foreach($file_array as $file_path){
	$lines = file($file_path);
	// loop through each line
	foreach ($lines as $line){
	// skip it if it's a comment 
	if (substr($line, 0, 2) == '--' || $line == '')
		  continue;
	// add this line to the current segment
	$templine .= $line;
	// if it has a semicolon at the end, it's the end of the query
		if (substr(trim($line), -1, 1) == ';'){
				// perform the query
				db_query($templine) or print('error performing query \'<strong>' . $templine . '\': ' . mysql_error() . '<br /><br />');
				// reset temp variable to empty
				$templine = '';
		}
	}

}
 drupal_set_message("Data imported successfully");

}
/**
* Implementation of hook_uninstall().
*/
function lp_testdata_uninstall() {
     db_query('TRUNCATE TABLE  `liveparcels_package` ;');
  db_query('TRUNCATE TABLE  `liveparcels_zone_post` ;');
  db_query('TRUNCATE TABLE  `liveparcels_zone_price` ;');
 
}


