<?php

function lp_qrcode_node_view($node, $view_mode) {

    if ($node->type=="live_parcel"){

	include "phpqrcode/qrlib.php";
	drupal_add_css(drupal_get_path('module','lp_qrcode').'/parcel.css');
        global $base_url;
        $data = '{"nid":'.$node->nid.',"title":"'.$node->title.'","url":"'.$base_url.'/node/'.$node->nid.'"}';
        QRcode::png($data, 'sites/default/files/'.$node->nid.$node->field_parcel_order_id['und'][0]['value'].'.png', "L", 4, 4);
        $code = '<img src="/sites/default/files/'.$node->nid.$node->field_parcel_order_id['und'][0]['value'].'.png"/>';

        $node->content['parcel_detail'] = array(
	  '#prefix' => '<div class="parcel_detail">',
  	  '#suffix' => '</div>',
    	  '#weight'=>-100,
	);

	$node->content['parcel_detail']['sub_title'] = array(
	  '#markup'=>'<h3>'.t('Parcel Details').'</h3>',
	); 
	$node->content['parcel_detail']['qrcode'] = array(
    	  '#markup' => '<div class="prcode">'.$code.'</div>',
 	);
	$node->content['parcel_detail']['parcel_order_id'] = $node->content['field_parcel_order_id'];
	$node->content['parcel_detail']['parcel_price'] = $node->content['field_parcel_price'];
	$node->content['parcel_detail']['parcel_size'] = $node->content['field_parcel_size'];
	$node->content['parcel_detail']['parcel_package_name'] = $node->content['field_parcel_package_name'];
	$node->content['parcel_detail']['parcel_weight'] = $node->content['field_parcel_weight'];
	$node->content['parcel_detail']['authority_to_leave'] = $node->content['field_authority_to_leave'];
	$node->content['parcel_detail']['cash_to_collect'] = $node->content['field_cash_to_collect'];
	$node->content['parcel_detail']['customer_reference'] = $node->content['field_customer_reference'];
	$node->content['parcel_detail']['fee_status'] = $node->content['field_fee_status'];

        hide($node->content['field_parcel_order_id']);
        hide($node->content['field_parcel_price']);
        hide($node->content['field_parcel_size']);
        hide($node->content['field_parcel_package_name']);
        hide($node->content['field_parcel_weight']);
        hide($node->content['field_authority_to_leave']);
        hide($node->content['field_cash_to_collect']);
        hide($node->content['field_customer_reference']);
        hide($node->content['field_fee_status']);

        $node->content['address'] = array(
    	  '#type' => 'fieldset',
	  '#title'=> t('Address settings'),
    	  '#weight' => -99,
	  '#collapsible' => TRUE,
  	  '#collapsed' => FALSE,
 	);
	$node->content['address']['pickup'] = array('#prefix'=>'<div class="pickup_info">','#suffix'=>'</div>'); 
	$node->content['address']['delivery'] = array('#prefix'=>'<div class="delivery_info">','#suffix'=>'</div>');      
        $node->content['address']['pickup']['pickup_note'] = $node->content['field_pickup_note'];
        $node->content['address']['pickup']['pickup_date'] = $node->content['field_pick_up_time'];
        $node->content['address']['pickup']['pickup_time_ampm'] = $node->content['field_pick_up_time_ampm'];
        $node->content['address']['pickup']['pickup_location'] = $node->content['field_pickup_location'];

        $node->content['address']['delivery']['delivery_note'] = $node->content['field_delivery_note'];
        $node->content['address']['delivery']['delivery_location'] = $node->content['field_delivery_location'];
        hide($node->content['field_pickup_note']);
        hide($node->content['field_pick_up_time']);
        hide($node->content['field_pick_up_time_ampm']);
        hide($node->content['field_pickup_location']);
        hide($node->content['field_delivery_note']);
        hide($node->content['field_delivery_location']);

        $node->content['parcel_updates'] = array(
    	  '#type' => 'fieldset',
	  '#title'=> t('Parcel Updates'),
    	  '#weight' => -97,
	  '#collapsible' => TRUE,
  	  '#collapsed' => FALSE,
 	);
        $node->content['parcel_updates']['parcel_comment'] = $node->content['comments'];
	$node->content['comments'] =  array();
        
         return $node;
    }   
}


