<?php
function lp_discount_menu(){
  $items['admin/liveparcels/discounts'] = array(
      'title' => t('Discount settings'), 
      'page callback' => 'drupal_get_form',
      'page arguments' => array('lp_discount_settings'),
      'access arguments' => array('administer actions'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'lp_discount.admin.inc',
      );
  return $items;
}

function lp_discount_roles_rate($tid){
  $rate = lp_discount_get_rate('roles',$tid);
  if($rate){
    return $rate;
  }else{
    return 1;
  }
}
function lp_discount_user_rate($tid){
  $rate = lp_discount_get_rate('user',$tid);
  if($rate){
    return $rate;
  }else{
    return 1;
  }
}

function lp_discount_get_rate($type='',$tid=0){
  if($type!=''){
    $result = db_query("SELECT rate FROM {live_parcel_discount} WHERE type = :type AND tid=:tid", array(':type' => $type, ':tid' => $tid))->fetchField();
    return $result;
  }else{
    return;

  }
}
function lp_discount_theme(){
  $theme_hooks = array(
      'user_wrapper' => array(
        'render element' => 'form',
        ),
      );   
  return  $theme_hooks;
}
function lp_discount_get_pricing($amount) {
    $amount=intval($amount);
  if(!$amount) {
    return 0;
  }

  global $user;
  $user_rate = lp_discount_user_rate($user->uid);
  if($user_rate != 1) {
    return ($amount*$user_rate);
  }else{
      $user_roles = user_roles();
      $user_role = $user->roles;
      $temp = (array_intersect_key($user_roles,$user_role));
      $temp = (array_slice($temp,-1,1,TRUE));
      $roles = (key($temp));
      $roles_rate = lp_discount_roles_rate($roles);
      return ($amount*$roles_rate);
    }
}
