<?php

/**
 * @file
 * Add company name fields to Location address.
 */

/**
 * Implements hook_locationapi().
 */
function location_company_locationapi(&$location, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'fields':
      return array('company' => t('Company name'));

    case 'defaults':
      return array(
        'company' => array('default' => '', 'collect' => 0, 'weight' => 25),
      );

    case 'field_expand':
      if ($a3 == 'company') {
        return array(
          '#type' => 'textfield',
          '#title' => t('Company name'),
          '#size' => 60,
          '#maxlength' => 200,
          '#description' => NULL,
          '#required' => ($a4['collect'] == 2),
          '#default_value' => $location,
        );
      }
      break;

    case 'save':
      db_delete('location_company')
        ->condition('lid', $location['lid'])
        ->execute();
      if (!empty($location['company'])) {
        db_insert('location_company')
          ->fields(array(
            'lid' => $location['lid'],
            'company' => $location['company'],
          ))
          ->execute();
      }
      break;

    case 'load':
      $fields = array();
      $company = db_query('SELECT company FROM {location_company} WHERE lid = :lid', array(':lid' => $location['lid']))->fetchField();
      $fields['company'] = $company ? $company : '';
      return $fields;

    case 'delete':
      db_delete('location_company')
        ->condition('lid', $location['lid'])
        ->execute();
      break;
  }
}

/**
 * Implements hook_views_api().
 */
function location_company_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_token_list().
 */
function location_company_token_list($type = 'all') {
  if ($type == 'node' || $type == 'user' || $type == 'all') {
    $tokens['location']['location-company_N'] = t('Location Company name (If there are multiple locations per node, N is the iteration, starting with 0)');
    return $tokens;
  }
}
